### PR TITLE
Do not limit/truncate API results

### PR DESCRIPTION
**Pull request by tpounds**
Removes request limits/truncation across the remaining plugins. It is similar to pull requests #5, #6, and #15.

### CODE REVIEW

**Comment by matthewdfuller** [comment]
I'm going to need to modify this one a bit because the limits checked for here (>1000 instances, 100 keys, etc.) are actually imposed by the AWS API. So theoretically, the code will need to check for the "NextToken" property of the response and then recursively call the same endpoint again until it is null. See: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#describeInstances-property

**Comment by tpounds** [comment]
I don't think this has to be modified as-is to be merged. It's only removing the limits and defers to the AWS defaults. That said, I do agree that every plugin should be updated to support proper pagination. I'm actually working on a series of commits to add support for that. I'll send a pull request for a single plugin so you can see the approach I am taking.

**Comment by tpounds** [comment]
FWIW, we have a really large AWS account with lots of resources across multiple services. About half of the plugins are only returning partial results either due to truncation or lack of pagination support.

**Comment by matthewdfuller** [comment]
Okay perfect, thanks so much for working on that. I agree - this would be preferable to adding an "unknown" result to some of them. My reasoning behind that was that at least you are *aware* things are being truncated. But with the added pagination support, we won't need this anymore.

**Comment by tpounds** [comment]
I agree it's preferable to emit a warning than silently ignore subsequent results. I'll try to get the other changes in a pull request ASAP.

**Comment by matthewdfuller** [comment]
@tpounds - Apologies for the (very late) ping on this PR, but we were performing an evaluation of code contributed to CloudSploit and realized we don't have a license agreement in place for you. Would you mind using the below link to review and digitally-sign CloudSploit's CLA? Thanks in advanced!

https://cla-assistant.io/cloudsploit/scans

**Pull request merged**
